config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  authenticated :user do
    root 'users#index', as: :authenticated_root
  end

  root to: 'pages#home'

  get '/widou-analytics' => 'pages#analytics'

  resources :users, only: [:index]

  resources :families, only: [:new, :create] do
    resources :missions, only: [:index, :new, :create]
    resources :rewards, only: [:index, :new, :create]
    resources :children, only: [:index, :new, :create]

  end
  resources :families, only: [:index, :show]
  resources :children, only: [:show]
  resources :missions, only: [:show, :edit, :update, :destroy]
  resources :rewards, only: [:show, :edit, :update, :destroy]
  resources :partnairs, only: [:index, :show, :edit, :update, :destroy, :new, :create]

end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]

  def index
    @family = User.where(family: current_user.family)
    @family_rewards = Reward.where(user: @family)
    @rewards = Reward.where(family: current_user.family)
    @rewards = policy_scope(current_user.rewards)
  end

  def show
  end

  def new
    @family = Family.find(params[:family_id])
    @reward = Reward.new
    @children = User.where(family: current_user.family).where(child: true)
    @partnairs = Partnair.all.collect(&:name)
    authorize @reward
  end

  def create
    @reward = Reward.new(rewards_params)
    @family = Family.find(params[:family_id])
    authorize @reward
    if @reward.save
      redirect_to family_rewards_path(current_user.family.id)
      flash[:alert] = "Votre récompense a bien été créée"
    else
      puts "fail"
      render new
    end
  end

  def edit
    @children = User.where(family: current_user.family).where(child: true)
  end

  def update
    @reward.update(rewards_params)
    @user = @reward.user
    if @reward.done?
      @user.point -= @reward.price
      @user.save
      redirect_to family_rewards_path(current_user.family.id)
      flash[:notice] = "C'est parti pour profiter un MAXXXX"
    else
      redirect_to family_rewards_path(current_user.family.id)
      flash[:notice] = "Il semble que quelquechose se soit mal passé... Réessaye"
    end
  end

  def destroy
    @reward.destroy
    redirect_to family_rewards_path(current_user.family.id)

  end

  private

  def set_reward
    @reward = Reward.find(params[:id])
    authorize @reward
  end

  def rewards_params
    params.require(:reward).permit(:user_id, :name, :price, :done)
  end
end

app/views/rewards/edit.html.erb
<div class="home page-container page-container--center">

  <%= render 'shared/navbar' %>

  <div class="family-creation-form">
    <h1><%= @reward.name %></h1>
    <%= simple_form_for [@family, @reward] do |f| %>
      <%= f.input :name, label: 'Nom de la récompense', placeholder: 'Nom de la récompense' %>
      <%= f.input :price, input_html: { class: 'input'}, label: 'Score à atteindre', collection: 1..50, include_blank: false %>
      <%= f.button :submit, 'Modifier la récompense', class: 'btn button-subscribe' %>
   <% end %>

   <%= link_to "Voir la liste de nos partenaires", partnairs_path, class: 'link' %> 
</div>

  <button type="button" class="btn"><%= link_to "Retour", :back,  class: 'btn button-subscribe' %></button>

  <%= render 'shared/footer' %>
</div>

app/views/rewards/index.html.erb
<div class="home page-container page-container--center">

  <%= render 'shared/navbar' %>

  <% if current_user.child? %>
  <!-- VUE ENFANT -->
  <h1>Mes récompenses</h1>
  <h1>Mon nombre de points disponible <%= @current_user.point %></h1>

    <div id="accordion">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h3 class="mb-0">
            <h1 data-toggle="collapse" data-target="#collapseOne" href="#collapse1">
              Les récompenses disponibles
            </h1>
          </h3>
        </div>
        <div id="collapseOne" class="collapse show" data-parent="#accordion">
          <div class="rewards-list">
            <% @current_user.rewards.order('price DESC').each do |reward| %>
              <% if reward.done? == false && reward.name.strip != "" %>
                <%= link_to reward_path(reward) do %>
                  <div class="available-reward">
                    <%= reward.name.capitalize %>
                    <p>Nombre de point requis <%= reward.price %></p>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="card">
        <div class="card-header" id="headingTwo">
          <h3 class="mb-0">
            <h1 data-toggle="collapse" data-target="#collapseTwo" href="#collapse2">
              Les récompenses déjà acquises
            </h1>
          </h3>
        </div>
        <div id="collapseTwo" class="collapse hide" data-parent="#accordion">
          <div class="rewards-list">
            <% @current_user.rewards.order('price DESC').each do |reward| %>
              <% if reward.done?  %>
                <%= link_to reward_path(reward) do %>
                <div class="available-reward">
                  <%= reward.name.capitalize %>
                  <p>Nombre de point requis <%= reward.price %></p>
                </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>


  <% else %>
  <!-- VUE PARENT -->

    <h1>Récompenses</h1>

    <button type="button" class="btn"><%= link_to "Ajouter une récompense",  partnairs_path, class: 'button-subscribe' %></button>

   <div class="rewards-list">
      <% @family_rewards.each do |reward| %>
        <% if reward.name.strip != "" %>
          <%= link_to reward_path(reward) do %>
            <div class="reward">
              <div class="reward__name">
                <%= "#{reward.name.capitalize} (#{reward.user.name})" %>
                <p>Nombre de points requis <%= reward.price %></p>
              </div>
          <% end %>
              <div class="reward__cta">
              <% if reward.done? %>
                <%= link_to "Information", reward_path(reward), class: 'button-small' %>
              <% else %>
                <%= link_to "Modifier", edit_reward_path(reward), class: 'button-small' %>
              <% end %>
                <%= button_to "Supprimer", reward, class: 'button-small', :method => :delete %>
              </div>     
          </div>
        <% end %>
      <% end %>
  </div>
    
  <% end %>

<!-- Lien vers ajouter une récompense => amène dans un premier temps sur la liste des partenaires -->

  <button type="button" class="btn"><%= link_to "Retour", :back,  class: 'btn button-subscribe' %></button>

 <%= render 'shared/footer' %>
</div>

app/views/rewards/new.html.erb
<div class="home page-container page-container--center">

  <%= render 'shared/navbar' %>

  <div class="family-creation-form">
    <h1>Ajouter une récompense personnalisée</h1>
    <%= simple_form_for [@family, @reward] do |f| %>
      <%= f.input :name, label: 'Nom de la récompense', placeholder: 'Nom de la récompense', input_html: { required: true }, include_blank: false %>
      <%= f.input :price, input_html: { class: 'input'}, label: 'Score à atteindre', collection: 1..50, include_blank: false %>
      <%= f.association :user, input_html: { class: 'input'}, label: 'Selectionner un enfant', collection: @children, include_blank: false%>
      <%= f.button :submit, 'Créer la récompense', class: 'btn button-subscribe' %>
    <% end %>

    <%= link_to "Voir la liste de nos partenaires", partnairs_path, class: 'link' %> 
  </div>
  <br/>

  <div class="family-creation-form">
    <h1>Ajouter une récompense via nos partenaires</h1>
    <%= simple_form_for [@family, @reward] do |f| %>
      <%= f.input :name, label: 'Liste de nos partenaires', collection: @partnairs %>
      <%= f.input :price, input_html: { class: 'input'}, label: 'Score à atteindre', collection: 1..50, include_blank: false %>
      <%= f.association :user, input_html: { class: 'input'}, label: 'Selectionner un enfant', collection: @children, include_blank: false%>
      <%= f.button :submit, 'Créer la récompense', class: 'btn button-subscribe' %>
    <% end %>

  </div>
  <button type="button" class="btn"><%= link_to "Retour", :back,  class: 'btn button-subscribe' %></button>

  <%= render 'shared/footer' %>
</div>




 

app/views/rewards/show.html.erb
<div class="home page-container page-container--center">
  <%= render 'shared/navbar' %>

  <div class="family-creation-form">
    <h1><%= @reward.name %></h1>

    <!-- VUE ENFANT -->
    <% if current_user.child? %>
      <p>Nombre de points requis : <%= @reward.price %></p>
        <% if current_user.point >= @reward.price && @reward.done == false %>
          <%= "JE LE VEUX !" %>
          <%= simple_form_for @reward do |f| %>
            <%= f.hidden_field :done, :value => true %>
            <%= f.button :submit, "C'est parti", class: 'btn button-widou' %>
             
          <% end %>
        <% elsif @reward.done %>
          <%= "Hep hep tu as déjà pris tout ça petit garnement" %>
        <% else %>
          <%= "Il te manque encore #{@reward.price - current_user.point} points" %>
        <% end %>

    <!-- VUE PARENT -->
    <% else %>
          <br />
      <% if @reward.done %>
      <% partnair = Partnair.find_by_name(@reward.name) %>
       <h3 style="text-align: center"><%= "La récompense a été selectionnée" %></h3>
          <% if partnair != nil && @reward.name == partnair.name %>
          <br />
          <br />
          <br />
            <h4><%=  "Code promo : #{partnair.code}" %></h4>
          <% else %>
          <%= "Pas de code promo pour cette récompense" %>
          <% end %>
          <br />
          <br />
          <%= "Pensez à supprimer la récompense" %>
      <% else %>
        <%= "La récompense n'a toujours pas été prise" %>
      <% end %>
    <% end %>
  </div>



  <button type="button" class="btn"><%= link_to "Retour", :back,  class: 'btn button-subscribe' %></button>

  <%= render 'shared/footer' %>

</div>