config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  authenticated :user do
    root 'users#index', as: :authenticated_root
  end

  root to: 'pages#home'

  get '/widou-analytics' => 'pages#analytics'

  resources :users, only: [:index]

  resources :families, only: [:new, :create] do
    resources :missions, only: [:index, :new, :create]
    resources :rewards, only: [:index, :new, :create]
    resources :children, only: [:index, :new, :create]

  end
  resources :families, only: [:index, :show]
  resources :children, only: [:show]
  resources :missions, only: [:show, :edit, :update, :destroy]
  resources :rewards, only: [:show, :edit, :update, :destroy]
  resources :partnairs, only: [:index, :show, :edit, :update, :destroy, :new, :create]

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :family
  has_many :rewards
  has_many :missions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  skip_before_action :require_no_authentication, only: [:new, :create, :cancel]
  #créée l'enfant mais se connecte dessus cf sign_up pour empecher

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  def sign_up(resource_name, resource)
    if current_user
      true #empeche toute connection après le sign up (même premier creation)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :family_id,
      :child,
      :name,
      :birth_date,
      :point
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = policy_scope(User)
    @family = User.where(family: current_user.family)
    @family_missions = Mission.where(user: @family)
    @family_rewards = Reward.where(user: @family)
  end

  def new
    @child = User.new
    authorize @child
  end

  def create
    @child = User.new(params[:child])
    authorize @child
    if @child.save
      UserMailer.welcome(@child).deliver_now
      redirect_to childrens_path
    else 
      render :new
    end
  end
end

app/views/users/index.html.erb
<div class="home page-container page-container--center">
  <%= render 'shared/navbar' %>

  <div class="main-content">
    <h1>Tableau de bord</h1>
  
    <div class=" dashboard-grid">
    

    <!-- PAGE ENFANT -->
    <% if current_user.child? %>

    
          <%= link_to 'Mes missions', family_missions_path(current_user.family), class: 'button-dashboard' %>
      
          <%= link_to 'Mes récompenses', family_rewards_path(current_user.family), class: 'button-dashboard'%>
    

    <!-- PAGE PARENT -->
    <!-- D'après moi, il faut afficher les 4 infos sous forme de carrés cliquable voir : Appli TBM (itinéraire horaire proximité trafic) mais en plus gros et plus beau -->

    <% else %>
    <!-- Première co -->
      <% if current_user.family.user.where(child: true).last == nil %>
        <%= link_to "Ajouter votre premier enfant", new_family_child_path(current_user.family_id),  class: 'btn button-subscribe' %>
      <% else %>
    <!-- Vue normale -->
        
          
            <%= link_to 'Mes enfants', family_children_path(current_user.family), class: 'button-dashboard' %>
          
    <!-- Première co -->
          <% if @family_missions.last == nil %>
            <%= link_to "Ajoutons une première mission", new_family_mission_path(current_user.family.id), class: 'button-dashboard' %>
          <% else %>
    <!-- Vue normale -->
            <div class="mission-notif">
              <%= link_to 'Les missions', family_missions_path(current_user.family), class: 'button-dashboard'%>
               <% if Mission.where(user: @family).where(:status => 'pending').count > 0 %>
                <div class="notification">
                  <%= Mission.where(user: @family).where(:status => 'pending').count %>
                </div>
        <% end %>
            </div>
    <!-- A placer qlq part sur le carré Mission -->
            
    <!-- Première co -->
            <% if @family_rewards.last == nil %>
              <%= link_to 'Ajoutons une récompense', partnairs_path, class: 'button-dashboard' %>
            <% else %>
    <!-- Vue normale  -->
              
                <%= link_to 'Les récompenses', family_rewards_path(current_user.family), class: 'button-dashboard'%>
              
              
                <%= link_to 'Nos partenaires', partnairs_path, class: 'button-dashboard' %>
              
            
            <% end %>
          <% end %>
      <% end %>
       
    <% end %>
    
    </div>
  </div>
  
<%= render 'shared/footer' %>

</div>