config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  authenticated :user do
    root 'users#index', as: :authenticated_root
  end

  root to: 'pages#home'

  get '/widou-analytics' => 'pages#analytics'

  resources :users, only: [:index]

  resources :families, only: [:new, :create] do
    resources :missions, only: [:index, :new, :create]
    resources :rewards, only: [:index, :new, :create]
    resources :children, only: [:index, :new, :create]

  end
  resources :families, only: [:index, :show]
  resources :children, only: [:show]
  resources :missions, only: [:show, :edit, :update, :destroy]
  resources :rewards, only: [:show, :edit, :update, :destroy]
  resources :partnairs, only: [:index, :show, :edit, :update, :destroy, :new, :create]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_flyout.html.erb
<% if current_user %>
<section class="flyout flyout-closed">
  <header class="flyout-header">
    <div class="d-flex justify-content-between">
      <a class="flyout-close icon-link" href="#">
          <%= image_tag("burger-menu.svg")  %>
      </a>
    </div>

    <div class="flyout-header-content">
        <span>Bienvenue sur Widou !</span>
        <span class="float-left"><%= "Content de te revoir #{current_user.name}" %></span>
    </div>

  </header>

    <div class="flyout-links">

      <%= link_to "Tableau de bord", users_path %>
      <% if current_user.child == false %>
        <%= link_to "Mes enfants", family_children_path(current_user.family) %>
      <% end %>
      <% if current_user.child?%>
        <%= link_to "Mes missions", family_missions_path(current_user.family) %>
      <% else %>
        <%= link_to "Les missions", family_missions_path(current_user.family) %>
      <% end %>
      <% if current_user.child? %>
        <%= link_to "Mes récompenses", family_rewards_path(current_user.family) %>
      <% else %>
        <%= link_to "Les récompenses", family_rewards_path(current_user.family) %>
      <% end %>
      <% if current_user.child == false %>
        <%= link_to 'Les partenaires', partnairs_path %>
      <% end %>
      <%= link_to "Mon compte", edit_user_registration_path %>
      <%= link_to "Se déconnecter",  destroy_user_session_path, method: :delete %>

    </div>

    <div class="flyout-bottom">
      Made with love
    </div>

  <div class="flyout-shadow flyout-close"></div>
</section>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    
    <%= image_tag 'bluesplash.png', class: 'blue-splash' %>

</div>

app/views/shared/_navbar.html.erb
<div class="header"> 
<div class="navbar">
    <a href="#" class="flyout-open">
      <svg width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M3 18H21V16H3V18ZM3 13H21V11H3V13ZM3 6V8H21V6H3Z" fill="black"/>
      </svg>
      <%= render 'shared/flyout' %>
    </a>
  </div>
   
  <%= link_to image_tag('logo-widou.png', class: 'logo'), root_path %>
    
</div>