config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  authenticated :user do
    root 'users#index', as: :authenticated_root
  end

  root to: 'pages#home'

  get '/widou-analytics' => 'pages#analytics'

  resources :users, only: [:index]

  resources :families, only: [:new, :create] do
    resources :missions, only: [:index, :new, :create]
    resources :rewards, only: [:index, :new, :create]
    resources :children, only: [:index, :new, :create]

  end
  resources :families, only: [:index, :show]
  resources :children, only: [:show]
  resources :missions, only: [:show, :edit, :update, :destroy]
  resources :rewards, only: [:show, :edit, :update, :destroy]
  resources :partnairs, only: [:index, :show, :edit, :update, :destroy, :new, :create]

end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :user
  enum status: [:to_do, :pending, :done]

end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]
  after_action :send_welcome_email, only: [:new]

  def index
    @family = User.where(family: current_user.family)
    @family_missions = Mission.where(user: @family)
    @missions = Mission.where(family: current_user.family)
    @missions = policy_scope(current_user.missions)
  end

  def show
  end

  def new
    @family = Family.find(params[:family_id])
    @mission = Mission.new
    @children = User.where(family: current_user.family).where(child: true)
    authorize @mission
  end

  def create
    @mission = Mission.new(mission_params)
    @family = Family.find(params[:family_id])
    @family_rewards = Reward.where(user: @family)
    authorize @mission
    if @mission.save
      if @family_rewards.last == nil
        redirect_to root_path
        flash[:notice] = "Votre mission a bien été créée"
      else
        redirect_to family_missions_path(current_user.family.id)
        flash[:notice] = "Votre mission a bien été créée"
      end
    else
      puts "fail"
      render new
    end
  end

  def edit
    @children = User.where(family: current_user.family).where(child: true)
  end

  def update
    @mission.update(mission_params)
    @user = @mission.user
    if current_user.child?
      redirect_to family_missions_path(current_user.family.id)
      flash[:notice] = "Le grand chef va bientôt venir vérifier tout ça"
    else
      if @mission.done?
        @mission.user.point += @mission.point
        @user.save
        redirect_to family_missions_path(current_user.family.id)
        flash[:notice] = "Votre sentence est envoyée"
      else
        redirect_to family_missions_path(current_user.family.id)
        flash[:notice] = "Votre sentence est envoyée"
      end
    end
  end

  def destroy
    @mission.destroy
    redirect_to family_missions_path(current_user.family.id)
  end

  private

  def set_mission
    @mission = Mission.find(params[:id])
    authorize @mission
  end

  def mission_params
    params.require(:mission).permit(:user_id, :start_at, :end_at, :point, :name, :status, :repition)
  end

  def send_welcome_email
    if ((User.last.missions.first == nil) && (User.last.child? == true) && (User.last.family.id == current_user.family.id) && (User.last.created_at.day == Time.current.day)) 
      UserMailer.welcome(User.last).deliver_now!
    end
  end
end

app/views/missions/edit.html.erb
<div class="home page-container page-container--center">
  <%= render 'shared/navbar' %>

  <div class="family-creation-form">
    <h1><%= @mission.name %></h1>
    <div class="family-creation-form">
      <%= simple_form_for [@family, @mission] do |f| %>
        <%= f.input :name, label: 'Nom de la mission', placeholder: 'Nom de la mission'%>
        <%= f.input :point, input_html: { class: 'input' },  label: 'Nombre de point(s) gagné(s)', collection: 1..20, include_blank: false, class: 'btn button-subscribe' %>
        <%= f.input :repition, input_html: { class: 'input'}, label: 'Récurrence (chaque jour)?', as: :select, include_blank: false, collection: [['Oui', true],['Non', false]] %>
      <%= f.button :submit, "Modifier la mission" ,class: 'btn button-subscribe' %>
    <% end %>
  </div>

  </div>
  <button type="button" class="btn"><%= link_to "Retour", :back,  class: 'btn button-subscribe' %></button>

  <%= render 'shared/footer' %>
</div>

app/views/missions/index.html.erb
<% @family_missions.where(repition: true).each do |mission| %>
  <% if ((mission.updated_at.day != Time.current.day) && mission.status == "done" ) %>  
    <% mission.status = "to_do" %>  
    <% mission.save %>
  <% end %>
<% end %>

<div class="home page-container page-container--center">
    <%= render 'shared/navbar' %>
    <div class="missions__CTA">
      <% if current_user.child? %>
      <!-- VUE ENFANT -->

        <h1>Mes missions</h1>

        <div id="accordion">
          <div class="card">
            <div class="card-header" id="headingOne">
              <h2 class="mb-0">
                <a data-toggle="collapse" data-target="#collapseOne" href="#collapse1" class='mission-status-accordion'>
                  A faire
                </a>
              </h2>
            </div>
            <div id="collapseOne" class="collapse show" data-parent="#accordion">
              <div class="missions-list">
                
                <% @current_user.missions.each do |mission| %>
                <div class="">
                  <% if mission.status == 'to_do' && mission.name.strip != "" %>
                  <div class ="ongoing-mission-children__CTA">
                    <%= link_to mission_path(mission) do %>
                      <%= mission.name.capitalize %>
                      <br>
                      <p>Nombre de points rapportés par la mission : <%= mission.point %></p>
                    <% end %>
                  </div>
                  <% end %>
                  </div>
                <% end %>
                
                
              </div>
            </div>
          </div>

          <div class="card">
            <div class="card-header" id="headingTwo">
              <h2 class="mb-0">
                <a data-toggle="collapse" data-target="#collapseTwo" href="#collapse2" class='mission-status-accordion'>
                   En cours de validation
                </a>
              </h2>
            </div>
            <div id="collapseTwo" class="collapse hide" data-parent="#accordion">
              <div class="missions-list">
                <% @current_user.missions.each do |mission| %>
                  <% if mission.status == 'pending' && mission.name.strip != "" %>
                    <div class ="ongoing-mission-children__CTA">  
                      <%= link_to mission_path(mission) do %>
                        <%= mission.name.capitalize %>
                        Nombre de points rapportés par la mission : <%= mission.point %>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>       
              </div>
            </div>
          </div>

          <div class="card">
            <div class="card-header">
              <h2 class="mb-0">
                <a data-toggle="collapse"  data-target="#collapseThree" class='mission-status-accordion'>
                  Ancienne mission
                </a>
              </h2>
            </div>
            <div id="collapseThree" class="collapse hide" data-parent="#accordion">
              <div class="missions-list">  
                <% @current_user.missions.each do |mission| %>
                  <% if mission.status == 'done' %>
                  <div class ="ongoing-mission-children__CTA"> 
                    <%= link_to mission_path(mission) do %>
                      <%= mission.name.capitalize %>
                      Nombre de points rapportés par la mission : <%= mission.point %>
                    <% end %>
                  </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>


        <% else %>

      <!-- VUE PARENT -->
      <h1>Missions en cours</h1>

      <button type="button" class="btn"><%= link_to "Ajouter une mission", new_family_mission_path(current_user.family.id),  class: 'btn button-subscribe' %></button>



      <div id="accordion">
        <div class="card">
          <div class="card-header" id="headingOne">
            <h2 class="mb-0">
              <h1 data-toggle="collapse" data-target="#collapseOne" href="#collapse1">
                A valider
              </h1>
            </h2>
          </div>
          <% if Mission.where(user: @family).where(:status => 'pending').count == 0 %>
            <div id="collapseOne" class="collapse hide" data-parent="#accordion">
          <% else %>
            <div id="collapseOne" class="collapse show" data-parent="#accordion">
          <% end %>
            <div class="missions-list">
              <% @family_missions.each do |mission| %>
                <% if mission.status == 'pending' && mission.name.strip != "" %>
                  <%= link_to mission_path(mission) do %>
                  <div class ="ongoing-mission-parents__CTA">
                    <%= "#{mission.name.capitalize} (#{mission.user.name})"%>
                  </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-header" id="headingTwo">
            <h2 class="mb-0">
              <h1 data-toggle="collapse" data-target="#collapseTwo" href="#collapse2">
                En cours
              </h1>
            </h2>
          </div>
          <% if (Mission.where(user: @family).where(:status => 'to_do').count > 0 && Mission.where(user: @family).where(:status => 'pending').count == 0)%>
            <div id="collapseTwo" class="collapse show" data-parent="#accordion">
          <% else %>
            <div id="collapseTwo" class="collapse hide" data-parent="#accordion">
          <% end %>

          <div class="missions-list">
            
            <% @family_missions.each do |mission| %>
              <div class="card-body ongoing-mission">
                <% if mission.status == 'to_do' && mission.name.strip != "" %>
                  <div class ="ongoing-mission__cta">
                    <%= link_to mission_path(mission) do %>
                        <%= "Pour #{mission.user.name} : #{mission.name.capitalize}" %>
                    <% end %>
                  </div>
                  <div class="ongoing-mission__links">
                    <%= link_to "modifier", edit_mission_path(mission), class: 'button-small'%>
                    <%= button_to "Supprimer",  mission,  class: 'button-small', :method => :delete %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="card">
          <div class="card-header" id="headingOne">
            <h2 class="mb-0">
              <h1 data-toggle="collapse" data-target="#collapseThree" href="#collapse1">
                Missions accomplies
              </h1>
            </h2>
          </div>
            <div id="collapseThree" class="collapse hide" data-parent="#accordion">
              <div class="missions-list">
                <% @family_missions.each do |mission| %>
                  <% if mission.status == 'done' %>
                    <%= link_to mission_path(mission) do %>
                    <div class ="ongoing-mission-parents__CTA">
                      <%= "#{mission.name.capitalize} (#{mission.user.name})"%>
                    </div>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>

      <% end %>

  <button type="button" class="btn"><%= link_to "Retour", :back,  class: 'btn button-subscribe' %></button>

  </div>

<%= render 'shared/footer' %>
</div>

app/views/missions/new.html.erb
<div class="home page-container page-container--center">
  <%= render 'shared/navbar' %>


  <% suggestions = ["faire son lit", "vider le lave vaisselle", "sortir les poubelles", "faire ses devoirs", "ramasser son linge sale", "ranger sa chambre", "ranger ses affaires au bon endroit", "nettoyer sa douche", "mettre la table", "vider la caisse du chat", "sortir le chien", "aller chercher le pain", "tondre la pelouse", "nourrir son animal domestique"] %>
 
  <div class="suggestion-container">
    <h1>Suggestions</h2>

    <div class="suggestion-grid">

      <% suggestions.each do |suggestion| %>
        <div class="button-suggestion">
            <%= suggestion.capitalize %>
      </div>
      <% end %>
    </div>
  </div>

    <h1>Ajouter une mission</h1>

  <div class="family-creation-form">
    
    <div class="family-creation-form">
      <%= simple_form_for [@family, @mission] do |f| %>
        <%= f.input :name, label: 'Nom de la mission', placeholder: 'Nom de la mission', presence: true %>
        <%= f.input :point, input_html: { class: 'input' },  label: 'Nombre de point(s) gagné(s)', collection: 1..20, include_blank: false, class: 'btn button-subscribe' %>
        <%= f.input :repition, input_html: { class: 'input'}, label: 'Récurrence (chaque jour)?', as: :select, include_blank: false, collection: [['Oui', true],['Non', false]] %>
        <%= f.association :user, input_html: { class: 'input'}, label: 'Quel enfant?', collection: @children, include_blank: false %>
      <%= f.button :submit, 'Créer la mission', class: 'btn button-subscribe' %>
    <% end %>
  </div>

  </div>

  <button type="button" class="btn"><%= link_to "Retour", :back,  class: 'btn button-subscribe' %></button>

  <%= render 'shared/footer' %>
</div>

app/views/missions/show.html.erb
<div class="home page-container page-container--center">
  <%= render 'shared/navbar' %>


  <div class ="family-creation-form">
    <h1><%= @mission.name.upcase %></h1>

    <% if current_user.child? %>
    <!-- VUE ENFANT -->
      <p>Début de la mission le : <%= @mission.start_at %></p>
      <p><%= "Si tu réussis, tu pourras obtenir #{@mission.point} #{(@mission.point == 1) ? "point" : "points" } !" %></p>

      <% if @mission.to_do?  %>
        <%= simple_form_for @mission do |f| %>
          <%= f.hidden_field :status, :value => 'pending' %>
          <%= f.button :submit, "J'ai terminé la mission", class: 'btn button-widou' %>
        <% end %>
      <% elsif @mission.pending? %>
        <p><%= "En cours de vérification par le Big Boss" %></p>
      <% else %>
        <p><%= "Bravo bien joué !" %></p>
      <% end %>

    <% else %>
    <!-- VUE PARENT -->
      <p><%= "Assigné à #{@mission.user.name}"%></p>
      <p>Nombres de points rapportés : <%= @mission.point %></p>
      <p><% if @mission.to_do? %>
          <%= "Mission toujours en cours" %>
        <% elsif @mission.pending? %>
          <%= "Vérifie que la mission a été correctement effectuée" %>
          <div class="validation-buttons">
            <%= simple_form_for @mission do |f| %>
              <%= f.hidden_field :status, :value => 'done' %>
              <%= f.button :submit, 'parfait', class: 'btn btn-success' %>
            <% end %>

            <%= simple_form_for @mission do |f| %>
              <%= f.hidden_field :status, :value => 'to_do' %>
              <%= f.button :submit, 'à refaire', class: 'btn btn-danger' %>
            <% end %>
          </div>
        <% else %>
          <%= "Mission réalisé avec Brio on peut être fière" %>
        <% end %>
      </p>
    <% end %>
  </div>

  <!-- 3 états différents : en cours(to_do[0])  / a valider(pending[1]) / valider(done[2]) -->

    <button type="button" class="btn"><%= link_to "Retour", :back,  class: 'btn button-subscribe' %></button>

  <%= render 'shared/footer' %>
</div>